Switch to using deb822 sources

diff --git a/debian/repository-dist.preinst b/debian/repository-dist.preinst
--- a/debian/repository-dist.preinst
+++ b/debian/repository-dist.preinst
@@ -16,37 +16,37 @@ true "
 "
 
 ## legacy
-if test -f /etc/apt/sources.list.d/whonix.list ; then
-   if ! test -f /etc/apt/sources.list.d/derivative.list ; then
-      mv --verbose /etc/apt/sources.list.d/whonix.list /etc/apt/sources.list.d/derivative.list
-   fi
-fi
+#if test -f /etc/apt/sources.list.d/whonix.list ; then
+#   if ! test -f /etc/apt/sources.list.d/derivative.list ; then
+#      mv --verbose /etc/apt/sources.list.d/whonix.list /etc/apt/sources.list.d/derivative.list
+#   fi
+#fi
 
 ## legacy
-rm --verbose --force /etc/apt/trusted.gpg.d/whonix.gpg
-rm --verbose --force /etc/apt/trusted.gpg.d/derivative.gpg
-rm --verbose --force /etc/apt/trusted.gpg.d/derivative.asc
-
-file_name="/etc/apt/sources.list.d/derivative.list"
+#rm --verbose --force /etc/apt/trusted.gpg.d/whonix.gpg
+#rm --verbose --force /etc/apt/trusted.gpg.d/derivative.gpg
+#rm --verbose --force /etc/apt/trusted.gpg.d/derivative.asc
+#
+#file_name="/etc/apt/sources.list.d/derivative.list"
 
 ## legacy
-if test -f "$file_name" ; then
-   ## Do not try to upgrade http to https as this would fail for onions.
-
-   search="deb tor+http"
-   replace="deb [signed-by=/usr/share/keyrings/derivative.asc] tor+http"
-   str_replace "$search" "$replace" "$file_name" >/dev/null || true
-   search="deb http"
-   replace="deb [signed-by=/usr/share/keyrings/derivative.asc] http"
-   str_replace "$search" "$replace" "$file_name" >/dev/null || true
-
-   search="deb-src tor+http"
-   replace="deb-src [signed-by=/usr/share/keyrings/derivative.asc] tor+http"
-   str_replace "$search" "$replace" "$file_name" >/dev/null || true
-   search="deb-src http"
-   replace="deb-src [signed-by=/usr/share/keyrings/derivative.asc] http"
-   str_replace "$search" "$replace" "$file_name" >/dev/null || true
-fi
+#if test -f "$file_name" ; then
+#   ## Do not try to upgrade http to https as this would fail for onions.
+#
+#   search="deb tor+http"
+#   replace="deb [signed-by=/usr/share/keyrings/derivative.asc] tor+http"
+#   str_replace "$search" "$replace" "$file_name" >/dev/null || true
+#   search="deb http"
+#   replace="deb [signed-by=/usr/share/keyrings/derivative.asc] http"
+#   str_replace "$search" "$replace" "$file_name" >/dev/null || true
+#
+#   search="deb-src tor+http"
+#   replace="deb-src [signed-by=/usr/share/keyrings/derivative.asc] tor+http"
+#   str_replace "$search" "$replace" "$file_name" >/dev/null || true
+#   search="deb-src http"
+#   replace="deb-src [signed-by=/usr/share/keyrings/derivative.asc] http"
+#   str_replace "$search" "$replace" "$file_name" >/dev/null || true
+#fi
 
 true "INFO: debhelper beginning here."
 
