add transports

diff --git a/usr/bin/repository-dist b/usr/bin/repository-dist
--- a/usr/bin/repository-dist
+++ b/usr/bin/repository-dist
@@ -153,7 +153,29 @@ man $SCRIPTNAME"
                fi
                shift 2
                ;;
-            ## TODO
+           -u | --url)
+                url="$2"
+                if [ "$url" != "whonix" ] && [ "$url" != "kicksecure" ]; then
+                    echo "ERROR: url can only be 'whonix' or 'kicksecure'."
+                    exit 1
+                fi
+                shift 2
+                ;;
+
+           -t | --transport)
+                transport="$2"
+                if [ -z "${transport}" ]; then
+                    echo "ERROR: transport must not be empty. Choose between:
+ plain-tls
+ plain-tls-tor
+ onion
+ onion-tls"
+                    exit 1
+                fi
+                shift 2
+                ;;
+
+             ## TODO
 #            -b | --baseuri)
 #                DERIVATIVE_APT_REPOSITORY_BASEURI="$2"
 #                if [ "$DERIVATIVE_APT_REPOSITORY_BASEURI" = "" ]; then
@@ -181,20 +203,22 @@ man $SCRIPTNAME"
 }
 
 parse_variables() {
-   if [ "$disable" = "1" ]; then
-      return 0
-   fi
-   if [ "$refresh_keys" = "1" ]; then
-      return 0
-   fi
+    [ "$disable" = "1" ] && return 0
+    [ "$refresh_keys" = "1" ] && return 0
 
-   if [ "$codename" = "" ]; then
+    if [ -z "$url" ]; then
+        echo "ERROR: url not provided, it can only be 'whonix' or 'kicksecure'"
+        exit 1
+    fi
+
+
+   if [ -z "$codename" ]; then
       [ -n "$codename_default_stable" ] || codename_default_stable="$(lsb_release --short --codename)"
 
       ## If codename_default_stable could not be set using lsb_release above, try to acquire it
       ## from /etc/debian_version.
       if [ "$codename_default_stable" = "n/a" ]; then
-         if cat /etc/debian_version | grep -q "/sid" ; then
+         if grep -q "/sid" /etc/debian_version ; then
             codename_default_stable="$(cat /etc/debian_version)"
             ## example codename_default_stable:
             ## bullseye/sid
@@ -207,37 +231,25 @@ parse_variables() {
       ## Remove eventual white spaces. Just in case.
       codename_default_stable="${codename_default_stable//[[:space:]]}"
 
-      if [ "$codename_default_stable" = "" ]; then
+      if [ -z "$codename_default_stable" ]; then
          echo "ERROR: codename auto detection failed! Please manually set ${under}--codename${reset}."
          exit 1
       fi
 
-      if [ "$repository" = "stable" ]; then
-         codename="$codename_default_stable"
-      elif [ "$repository" = "stable-proposed-updates" ]; then
-         codename="${codename_default_stable}-proposed-updates"
-      elif [ "$repository" = "testers" ]; then
-         codename="${codename_default_stable}-testers"
-      elif [ "$repository" = "developers" ]; then
-         codename="${codename_default_stable}-developers"
-      else
-         echo "ERROR: No option given. Usage examples:
-
-sudo $SCRIPTNAME --enable --repository stable
-
-sudo $SCRIPTNAME --verbose --enable --repository stable
-
-sudo $SCRIPTNAME --enable --codename $codename_default_stable
-
-sudo $SCRIPTNAME --disable
-
-sudo $SCRIPTNAME --disable --verbose
-
-See also:
-
-man $SCRIPTNAME"
-         exit 1
-      fi
+    case "$repository" in
+        stable) codename="$codename_default_stable";;
+        stable-proposed-updates) codename="${codename_default_stable}-proposed-updates";;
+        testers) codename="${codename_default_stable}-testers";;
+        developers) codename="${codename_default_stable}-developers";;
+        "") codename="$codename_default_stable";;
+        *)
+            echo "ERROR: Invalid repository option, available options are:
+ stable
+ stable-proposed-updates
+ testers
+ developers"
+            exit 1
+        esac
    fi
 
    codename_old="$codename"
@@ -269,62 +281,105 @@ disable_refresh_create() {
 }
 
 sources_list_generator() {
-   if echo "$codename" | grep -q -i "n/a" ; then
-      echo "ERROR: Autodetected codename '${under}$codename${reset}' is invalid!"
-      echo 'Please set codename explicitly using:'
-      echo '${under}--codename${reset}'
-      exit 1
-   fi
+    if echo "$codename" | grep -q -i "n/a" ; then
+        echo "ERROR: Autodetected codename '${under}$codename${reset}' is invalid!"
+        echo 'Please set codename explicitly using:'
+        echo '${under}--codename${reset}'
+        exit 1
+    fi
 
-   echo "INFO '$BASH_SOURCE': Using distribution '${under}$codename${reset}' (version of derivative) as apt repository."
-   echo "INFO '$BASH_SOURCE': Creating '${under}$sources_list_file_derivative${reset}'..."
+    case "$url" in
+        whonix)
+            url_onion="deb.dds6qkxpwdeubwucdiaord2xgbbeyds25rbsgr73tbfpqpt4a6vjwsyd.onion"
+            url_plain="deb.whonix.org"
+            sources_file="/etc/apt/sources.list.d/derivative.list"
+            ;;
+        kicksecure)
+            url_onion="deb.w5j6stm77zs6652pgsij4awcjeel3eco7kvipheu6mtr623eyyehj4yd.onion"
+            url_plain="deb.kicksecure.com"
+            sources_file="/etc/apt/sources.list.d/kicksecure.list"
+            ;;
+    esac
 
-   echo "\
-# Copyright (C) 2012 - 2021 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
-# See the file COPYING for copying conditions.
 
-# $sources_list_file_derivative
+    ## cover all possibilities, even lines with wrong syntax
+    transport_lines="
+http://${url_plain}
+https://${url_plain}
+tor+http://${url_plain}
+tor+https://${url_plain}
+http+tor://${url_plain}
+https+tor://${url_plain}
+http://${url_onion}
+https://${url_onion}
+tor+http://${url_onion}
+tor+https://${url_onion}
+http+tor://${url_onion}
+https+tor://${url_onion}
+"
 
-# This file has been automatically created by $SCRIPTNAME.
-# If you make manual changes to it, your changes get lost next time you run
-# the $SCRIPTNAME tool.
-# You can conveniently manage this file, using the $SCRIPTNAME tool.
-# For any modifications (delete this file, use stable version, use testers
-# version or use developers version), please use the $SCRIPTNAME tool.
-# Run:
-#    sudo $SCRIPTNAME
-" > "$sources_list_file_derivative"
+    ## syntax is prefixing with 'tor+http(s)' for uniformity
+    ## although 'http(s)+tor' also works.
+    case "$transport" in
+        plain-tls) repo="https://${url_plain}";;
+        plain-tls-tor) repo="tor+https://${url_plain}";;
+        onion) repo="tor+http://${url_onion}";;
+        onion-tls) repo="tor+https://${url_onion}";;
+        "") repo="tor+http://${url_onion}";; ## default to onion service
+        *) echo "ERROR: Invalid transport type, it can only be:
+ plain-tls
+ plain-tls-tor
+ onion
+ onion-tls"
+        exit 1
+        ;;
+    esac
 
-   #for baseuri in $DERIVATIVE_APT_REPOSITORY_BASEURI; do
-      echo "\
-#deb [signed-by=/usr/share/keyrings/derivative.asc] tor+http://deb.dds6qkxpwdeubwucdiaord2xgbbeyds25rbsgr73tbfpqpt4a6vjwsyd.onion $codename main contrib non-free
-#deb-src [signed-by=/usr/share/keyrings/derivative.asc] tor+http://deb.dds6qkxpwdeubwucdiaord2xgbbeyds25rbsgr73tbfpqpt4a6vjwsyd.onion $codename main contrib non-free
+    echo "INFO '$BASH_SOURCE': Using distribution '${under}$codename${reset}' (version of derivative) as apt repository."
+    echo "INFO '$BASH_SOURCE': Creating '${under}$sources_file${reset}'..."
 
-deb [signed-by=/usr/share/keyrings/derivative.asc] tor+https://deb.whonix.org $codename main contrib non-free
-#deb-src [signed-by=/usr/share/keyrings/derivative.asc] tor+https://deb.whonix.org $codename main contrib non-free
-" >> "$sources_list_file_derivative"
-   #done
+    echo "\
+## Copyright (C) 2012 - 2021 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
+## See the file COPYING for copying conditions.
 
-   echo "\
-# Leaving source line disabled by default to safe some time, it's not useful
-# anyway, since it's better to get the source code from the git repository.
+## $sources_list_file_derivative
 
-# End of $sources_list_file_derivative
-" >> "$sources_list_file_derivative"
+## This file has been automatically created by $SCRIPTNAME.
+## If you make manual changes to it, your changes get lost next time you run
+## the $SCRIPTNAME tool.
+## You can conveniently manage this file, using the $SCRIPTNAME tool.
+## For any modifications (delete this file, use stable version, use testers
+## version or use developers version), please use the $SCRIPTNAME tool.
+## Run:
+##    sudo $SCRIPTNAME
 
-   cat "$sources_list_file_derivative"
-   echo "INFO '$BASH_SOURCE': Done."
+deb [signed-by=/usr/share/keyrings/derivative.asc] $repo $codename main contrib non-free
+#deb-src [signed-by=/usr/share/keyrings/derivative.asc] $repo $codename main contrib non-free
+
+## Leaving source line disabled by default to save some time, it's not useful
+## anyway, since it's better to get the source code from the git repository.
+
+## End of $sources_file
+" | tee "$sources_file" >/dev/null
+
+    ## check every line possibility to be altered
+    #for line in ${transport_lines}; do
+    #    sed -i'' "s| ${line}| ${repo}|" "${sources_file}"
+    #done
+
+    cat "$sources_file"
+    echo "INFO '$BASH_SOURCE': Done."
 }
 
 main_function() {
-   root_check
-   sanity_tests
-   colors
-   preparation
-   parse_cmd_options "$@"
-   parse_variables
-   disable_refresh_create
-   sync
+    root_check
+    sanity_tests
+    colors
+    preparation
+    parse_cmd_options "$@"
+    parse_variables
+    disable_refresh_create
+    sync
 }
 
 main_function "$@"
