error out in case auto detected codename is "n/a"

diff --git a/usr/bin/whonix_repository b/usr/bin/whonix_repository
--- a/usr/bin/whonix_repository
+++ b/usr/bin/whonix_repository
@@ -274,6 +274,15 @@ man whonix_repository"
          exit 1
       fi
    fi
+
+   if [ "$codename" = "n/a" ]; then
+      echo "ERROR: Autodetected codename $codename is invalid!"
+      echo 'Above codename_default_stable="$(lsb_release --short --codename)" might
+have had output "n/a". This apparently happens when a Debian release is still unreleased.'
+      echo 'Please set codename explicitly using:'
+      echo '--codename'
+      exit 1
+   fi
 }
 
 enable_disable_refresh_keys() {
